services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: huwelijk
      POSTGRES_USER: huwelijk
      POSTGRES_PASSWORD: huwelijk
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
